[versions]
agp = "8.6.0"
androidMjpegView = "1.1.2"
ipcamViewVersion = "2.4.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"

[libraries]
android-mjpeg-view = { module = "com.perthcpe23.dev:android-mjpeg-view", version.ref = "androidMjpegView" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
niqdev-ipcam-view = { module = "com.github.niqdev:ipcam-view", version.ref = "ipcamViewVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

